version: '3.9'

services:

  app_a826:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_a826
    working_dir: /var/www/html
    command: >
      sh -c "composer install &&
             php-fpm"
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    restart: always

  nginx_a826:
    image: nginx:latest
    container_name: nginx_a826
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_a826
